# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and release

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Login to Github Packages
#        uses: docker/login-action@v1
#        with:
##            registry: ghcr.io
##            username: ${{ github.repository_owner }}
##            password: ${{ secrets.CR_PAT }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#          registry: docker.pkg.github.com
#
#      - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#            context: .
#            file: ./Dockerfile
#            pull: true
#            push: true
##            cache-from: type=registry,ref=dunctebot/dashboard:latest
##            cache-to: type=inline
#            tags: docker.pkg.github.com/dunctebot/dashboard/dashboard:latest

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: docker.pkg.github.com
            repository: dunctebot/dashboard/dashboard
            tags: latest

      - name: Trigger webhook
        uses: zzzze/webhook-trigger@v1.0.0
        with:
            webhook_url: ${{ secrets.WEBHOOK_URL }}
